### PR TITLE
Adding test_plotting in tests

### PR DESCRIPTION
**Pull request by FloraSauerbronn**
Creating test_plotting.py with the first test of plot_transect, using pytest-mpl.

### CODE REVIEW

**Review by ocefpaf — COMMENTED** [review]
We need 3 extra steps to activate the image comparison tests here:

1. add `pytest-mpl` to the `requirements-dev.txt` file..
2. generate the comparison images with `pytest --mpl-generate-path=tests/baseline`.
3. add the `--mpl` option in the line that run the tests in `.github/workflows/tests.yml`.

You can find more about `pytest-mpl` [here](https://pytest-mpl.readthedocs.io/en/stable/usage.html).

**Comment by ocefpaf** [comment]
@FloraSauerbronn, as you can see the PR is failing as expected when we change the plot and the image deviates from the baseline. We can revert it back to `temperature` now and things should pass.

**Comment by FloraSauerbronn** [comment]
> @FloraSauerbronn, as you can see the PR is failing as expected when we change the plot and the image deviates from the baseline. We can revert it back to `temperature` now and things should pass.

Sorry @ocefpaf, I forgot to change it back before the push

**Comment by ocefpaf** [comment]
The tests are failing now b/c there is enough difference to trigger a real mismatch. The diff image is:

image

That is probably b/c of fonts differences between you installation of matplotlib and the one in the CIs. BTW, what version of matplotlib do you have?

I'll regenerate the image here and push to confirm if that is the case.

**Comment by ocefpaf** [comment]
As I suspected, the matplolib on my machine was able to create an image that had a match with the one in the CIs. We could also get this to pass by adjust the tolerance but, in this case, we could solve it without resorting to that.

**Comment by ocefpaf** [comment]
pre-commit.ci autofix

**Comment by FloraSauerbronn** [comment]
> The tests are failing now b/c there is enough difference to trigger a real mismatch. The diff image is:
> 
> image
> 
> That is probably b/c of fonts differences between you installation of matplotlib and the one in the CIs. BTW, what version of matplotlib do you have?
> 
> I'll regenerate the image here and push to confirm if that is the case.

I'm using 
matplotlib                    3.9.0
matplotlib-inline             0.1.7

What is the CIs ?

**Comment by ocefpaf** [comment]
I'll merge this to reduce the merge conflicts and we can address the last pre-commit-ci failure in a new PR.

**Pull request merged**
