### PR TITLE
Re-factor docs and CIs to run within Travis-CI time limit

### PR DESCRIPTION
**Pull request by ocefpaf**
This should speed up the CIs a bit.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@LindsayRAbrams and @callumrollo I refactored the notebooks to get them to run quicker so we can use them to build the documentation. Now the plotting part lives in a separate notebook.

Do you mind taking a quick look at this PR?

**Comment by callumrollo** [comment]
Wooh! Passing checks. Cool to see the optimised snakepit tools at work too.

The notebook refactor looks good, much cleaner than before. However, gliderpy is not on conda-forge and I can't find it in PyPI either. Without the kludge I was using to add the gliderpy directory to path and install locally (see nbs prior to the last commit on master), I cannot import gliderpy functions, so the notebooks fail for me.

This probably stems from a misunderstaning on my part. Should I be using a workaround to install gliderpy locally? Like adding the directory to my PATH prior to launching Jupyter

**Comment by ocefpaf** [comment]
> However, gliderpy is not on conda-forge and I can't find it in PyPI either. Without the kludge I was using to add the gliderpy directory to path and install locally (see nbs prior to the last commit on master), I cannot import gliderpy functions, so the notebooks fail for me.

The goal is to issue a first release soon but we should create "dev docs" to teach people who want to experiment with the code to install it with `pip install -e . --no-deps --force-reinstall` in a fresh GitHub clone.

> This probably stems from a misunderstaning on my part. Should I be using a workaround to install gliderpy locally? Like adding the directory to my PATH prior to launching Jupyter

I'll write the docs but my workflow is mostly what is in the `.travis.yml` setup:

```shell
conda create --name GLIDERPY python=3.8 --file requirements.txt --file requirements-dev.txt
source activate TEST
pip install -e . --no-deps --force-reinstall
```

That will give you a Python 3.8 development installation in the GLIDERPY environment. I have an environment like that for each project and I usually remove and re-create them often. (Environments are "cheap" in conda.)

**Comment by callumrollo** [comment]
Following environment build instructions both notebooks run cleanly for me now. 

Good to merge :+1:

**Pull request merged**
