### PR TITLE
Update plotting2

### PR DESCRIPTION
**Pull request by FloraSauerbronn**
Update plotting.py, test_plotting and add new figures to tests/baseline/

### CODE REVIEW

**Comment by ocefpaf** [comment]
If you click on the links for the CIs above you can inspect the log and see the reason for the failures. In this case it is:

```
==================================== ERRORS ====================================
___________________ ERROR collecting tests/test_plotting.py ____________________
tests/test_plotting.py:14: in <module>
    @pytest.fixture
E   NameError: name 'pytest' is not defined
```

That means you need to `import pytest` in the `tests/test_plotting.py` module.

**Comment by FloraSauerbronn** [comment]
I can't figure out why the image tests are failing. On my local computer, the tests pass, even when I change parameters and they should fail. It seems that, for some reason, pytest is not functioning correctly in my local repository.

**Comment by ocefpaf** [comment]
Let me know when you are done writing the tests, I just answered you colobar question on slack, and I'll check what is going on with the figures. I suspect has  something to do with your matplotlib installation, fonts, etc. I'll re-generate the figures on my machine before merging.

**Comment by ocefpaf** [comment]
@FloraSauerbronn the error is probably due to different fonts in the matplotlib version you have vs the one in the CI system. See the image diff below:

result-failed-diff


We could adjust the tolerance but for now it is easier to just regenerate them in a system that has the same fonts.

**Comment by ocefpaf** [comment]
@FloraSauerbronn I updated the images and fixed a few lints. Mostly missing docstrings.

**Pull request merged**
