### PR TITLE
friendly server names with string matching function

### PR DESCRIPTION
**Pull request by callumrollo**
A first attempt at implementing friendly server names. The magic happens in the new servers.py file.

The logic is laid out in the function `server_select`. This tries various matches to the user supplied string:

If it matches a server http exactly, return unchanged
If it matches a server http, but has extra stuff on the end, return the server http only
If it matches a common alias e.g IOOS or ifremer, return the corresponding server (case insensitive)
If no match can be made, raise a ValueError and return a list of supported servers

The works for all the cases in Issue #38

I could be barking up the wrong tree with this. But if it makes sense as an implementation I'll write some tests for it

### CODE REVIEW

**Comment by ocefpaf** [comment]
@callumrollo sorry for the merge conflict. Do you want to fix this PR?

**Comment by callumrollo** [comment]
No worries. Does this fix it? Not merged conflicts on github before

**Comment by callumrollo** [comment]
I don't have write access to merge this I'm afraid @ocefpaf. Let me know if there are any other edits needed

**Comment by callumrollo** [comment]
Hi Filipe, hitting the same issue with setting off the CI here. Can you add me to the approved list for triggering checks?

**Comment by callumrollo** [comment]
@ocefpaf are we ok to merge this one?

**Pull request merged**
