### PR TITLE
Init update

### PR DESCRIPTION
**Pull request by FloraSauerbronn**
Updating init.py with plotting and fetchers functions

### CODE REVIEW

**Comment by ocefpaf** [comment]
@FloraSauerbronn there is no need to submit a new PR to add improvements to an existing one. You can implement these changes in #104. I can show you how to add commits to existing branches today during the call.

**Comment by Harish-2003** [comment]
Can I help you with any process?

**Comment by ocefpaf** [comment]
> Can I help you with any process?

Thanks for the offer to help @Harish-2003! As you probably already know GSoC is a earning environment that encourages contributions. We do have some meetings planned where we will go over the workflow process, PR submission, etc. That means these PRs are just a warm up. If you want, we can ping you when there are more complicated stuff to review that could use your expertise.

**Comment by ocefpaf** [comment]
@FloraSauerbronn as we discussed today this change will be included in #104.

**Comment by ocefpaf** [comment]
Closing this one now that we have #104 in.

**Pull request closed without merging**
